import numpy as np
import pandas as pd
from scipy import stats
from typing import Optional, List, Dict, Tuple, Union, Callable, Any

from bxai._utils.validation import check_array_2d


class BayLIMEExplanation:
    """Represents a local explanation generated by BayLIME.
    
    Contains the posterior mean, covariance, and credible intervals of the
    local explanation weights (surrogate coefficients).
    """

    def __init__(
        self,
        feature_names: List[str],
        intercept_mean: float,
        intercept_var: float,
        coef_mean: np.ndarray,
        coef_cov: np.ndarray,
        instance: np.ndarray,
        prediction: Union[float, np.ndarray],
        credible_mass: float = 0.95,
    ):
        self.feature_names = feature_names
        self.intercept_mean = intercept_mean
        self.intercept_var = intercept_var
        self.coef_mean = coef_mean
        self.coef_cov = coef_cov
        self.coef_std = np.sqrt(np.diag(coef_cov))
        self.instance = instance
        self.prediction = prediction
        self.credible_mass = credible_mass

    def credible_intervals(self, credible_mass: Optional[float] = None) -> Dict[str, Tuple[float, float]]:
        """Compute the credible interval bounds for each feature coefficient."""
        mass = credible_mass if credible_mass is not None else self.credible_mass
        q_lower = (1.0 - mass) / 2.0
        q_upper = 1.0 - q_lower
        
        intervals = {}
        for idx, name in enumerate(self.feature_names):
            mean = self.coef_mean[idx]
            std = self.coef_std[idx]
            # Normal posterior marginal distribution for weights
            lower = stats.norm.ppf(q_lower, loc=mean, scale=std)
            upper = stats.norm.ppf(q_upper, loc=mean, scale=std)
            intervals[name] = (lower, upper)
        return intervals

    def as_list(self) -> List[Tuple[str, float]]:
        """Return the explanation as a sorted list of (feature_name, mean_weight) tuples."""
        pairs = list(zip(self.feature_names, self.coef_mean))
        # Sort by absolute weight magnitude descending
        return sorted(pairs, key=lambda x: abs(x[1]), reverse=True)

    def as_dataframe(self, credible_mass: Optional[float] = None) -> pd.DataFrame:
        """Return a summary of the local explanation weights as a pandas DataFrame."""
        mass = credible_mass if credible_mass is not None else self.credible_mass
        intervals = self.credible_intervals(mass)
        
        data = []
        for idx, name in enumerate(self.feature_names):
            lower, upper = intervals[name]
            data.append({
                "feature": name,
                "mean": self.coef_mean[idx],
                "std": self.coef_std[idx],
                "hdi_lower": lower,
                "hdi_upper": upper,
                "value": self.instance[idx],
            })
            
        df = pd.DataFrame(data)
        # Sort by absolute mean value descending
        df["abs_mean"] = df["mean"].abs()
        df = df.sort_values("abs_mean", ascending=False).drop(columns=["abs_mean"])
        return df.reset_index(drop=True)

    def plot(self, credible_mass: Optional[float] = None, max_features: int = 10) -> Any:
        """Plot the explanation as a horizontal bar chart with credible intervals.
        
        Requires matplotlib.
        """
        try:
            import matplotlib.pyplot as plt
        except ImportError:
            raise ImportError("matplotlib is required to plot explanations. Install it with pip.")

        df = self.as_dataframe(credible_mass).head(max_features)
        df = df.iloc[::-1]  # Invert so largest is at the top
        
        fig, ax = plt.subplots(figsize=(8, len(df) * 0.4 + 1.5))
        
        # Plot error bars
        errors_lower = df["mean"] - df["hdi_lower"]
        errors_upper = df["hdi_upper"] - df["mean"]
        xerr = np.vstack([errors_lower, errors_upper])
        
        colors = ["#1f77b4" if m >= 0 else "#d62728" for m in df["mean"]]
        
        ax.barh(
            df["feature"],
            df["mean"],
            xerr=xerr,
            color=colors,
            alpha=0.8,
            error_kw={"ecolor": "dimgray", "capsize": 3, "lw": 1.5},
        )
        
        ax.axvline(0, color="black", linestyle="--", linewidth=1)
        ax.set_xlabel("Local Feature Importance (Posterior Mean)")
        ax.set_title(f"BayLIME Explanation (Credible Mass = {credible_mass if credible_mass else self.credible_mass})")
        plt.tight_layout()
        return fig


class BayLIME:
    """BayLIME Local Surrogate Explainer.
    
    Fits a Bayesian Ridge Regression over local perturbations to explain instance
    predictions with stability, prior injection capabilities, and uncertainty bounds.
    """

    def __init__(
        self,
        training_data: Any,
        feature_names: Optional[List[str]] = None,
        kernel_width: float = 0.75,
        num_samples: int = 5000,
        prior_mean: Optional[np.ndarray] = None,
        prior_precision: Optional[Union[float, np.ndarray]] = None,
        random_state: Optional[int] = None,
    ):
        self.training_data = check_array_2d(training_data)
        self.n_features = self.training_data.shape[1]
        
        if feature_names is not None:
            if len(feature_names) != self.n_features:
                raise ValueError(f"Length of feature_names ({len(feature_names)}) must match n_features ({self.n_features})")
            self.feature_names = feature_names
        else:
            self.feature_names = [f"feature_{i}" for i in range(self.n_features)]
            
        self.kernel_width = kernel_width
        self.num_samples = num_samples
        self.prior_mean = prior_mean
        self.prior_precision = prior_precision
        self.random_state = random_state
        
        # Calculate feature scales (means and standard deviations) for perturbation scaling
        self.means_ = np.mean(self.training_data, axis=0)
        self.stds_ = np.std(self.training_data, axis=0)
        # Avoid division by zero for constant features
        self.stds_[self.stds_ == 0.0] = 1.0

    def explain_instance(
        self,
        instance: np.ndarray,
        predict_fn: Callable[[np.ndarray], np.ndarray],
        label: int = 1,
        noise_scale: float = 0.1,
    ) -> BayLIMEExplanation:
        """Generate a BayLIME explanation for a single instance.
        
        Parameters
        ----------
        instance : np.ndarray
            The 1D instance vector to explain. Shape: (n_features,).
        predict_fn : Callable
            The prediction function of the black-box model. Takes a 2D array
            and returns a 2D array of predictions (probabilities or regression values).
        label : int, default=1
            The prediction label/column index to explain.
        noise_scale : float, default=0.1
            The scale of perturbation variance around the instance.
        """
        instance = np.asarray(instance, dtype=float).ravel()
        if len(instance) != self.n_features:
            raise ValueError(f"Instance length ({len(instance)}) must match n_features ({self.n_features})")

        rng = np.random.default_rng(self.random_state)

        # Generate perturbed sample neighborhood around the instance
        # Draw samples from a normal distribution around the instance, scaled by the feature standard deviations
        noise = rng.normal(0.0, noise_scale, size=(self.num_samples, self.n_features))
        Z = instance + noise * self.stds_
        
        # Ensure the first instance in neighborhood is the instance itself (standard LIME practice)
        Z[0] = instance

        # Calculate distances in normalized feature space
        Z_normalized = (Z - instance) / self.stds_
        distances = np.linalg.norm(Z_normalized, axis=1)
        
        # Calculate proximity weights using the exponential distance kernel
        proximity_weights = np.exp(-(distances ** 2) / (self.kernel_width ** 2))

        # Get black-box model predictions for the neighborhood
        preds = predict_fn(Z)
        if preds.ndim == 1:
            y = preds
        else:
            y = preds[:, label]

        # Prepare design matrix (with intercept)
        # shape: (num_samples, n_features + 1)
        X = np.hstack([np.ones((self.num_samples, 1)), Z])

        # Prior Elicitation for coefficients and intercept
        # theta = [intercept, coef_1, ..., coef_p]
        p = self.n_features
        mu_theta_0 = np.zeros(p + 1)
        if self.prior_mean is not None:
            prior_m = np.asarray(self.prior_mean).ravel()
            if len(prior_m) != p:
                raise ValueError(f"prior_mean length ({len(prior_m)}) must match n_features ({p})")
            mu_theta_0[1:] = prior_m

        # Prior Precision Matrix
        Sigma_theta_0_inv = np.zeros((p + 1, p + 1))
        # Flat prior (high variance/low precision) for the intercept
        Sigma_theta_0_inv[0, 0] = 1e-4
        
        if self.prior_precision is None:
            # Default to L2 regularization (Ridge-like) with prior precision = 1.0
            np.fill_diagonal(Sigma_theta_0_inv[1:, 1:], 1.0)
        elif isinstance(self.prior_precision, (int, float)):
            np.fill_diagonal(Sigma_theta_0_inv[1:, 1:], float(self.prior_precision))
        else:
            prior_p = np.asarray(self.prior_precision).ravel()
            if len(prior_p) != p:
                raise ValueError(f"prior_precision length ({len(prior_p)}) must match n_features ({p})")
            np.fill_diagonal(Sigma_theta_0_inv[1:, 1:], prior_p)

        # Closed-form Weighted Bayesian Linear Regression updates
        # Scale design matrix and targets by proximity weights
        X_weighted = X * proximity_weights[:, np.newaxis]
        XTWX = X_weighted.T @ X
        XTWy = X_weighted.T @ y

        # Calculate posterior covariance Sigma_n and mean mu_n
        try:
            Sigma_n = np.linalg.inv(XTWX + Sigma_theta_0_inv)
        except np.linalg.LinAlgError:
            # Fallback to pseudo-inverse if singular
            Sigma_n = np.linalg.pinv(XTWX + Sigma_theta_0_inv)
            
        mu_n = Sigma_n @ (XTWy + Sigma_theta_0_inv @ mu_theta_0)

        # Separate intercept and coefficients
        intercept_mean = mu_n[0]
        intercept_var = Sigma_n[0, 0]
        
        coef_mean = mu_n[1:]
        coef_cov = Sigma_n[1:, 1:]

        return BayLIMEExplanation(
            feature_names=self.feature_names,
            intercept_mean=intercept_mean,
            intercept_var=intercept_var,
            coef_mean=coef_mean,
            coef_cov=coef_cov,
            instance=instance,
            prediction=preds[0],
        )
