import numpy as np
import pandas as pd
from scipy import stats
from sklearn.base import BaseEstimator
from typing import Optional, List, Dict, Tuple, Union, Callable, Any

from bxai._utils.validation import check_array_2d
from bxai._utils.hdi import compute_hdi



class BayLIMEExplanation:
    """Represents a local explanation generated by BayLIME.

    Contains the posterior mean, covariance (analytical backend) or full posterior
    draws (MCMC backend), plus credible intervals of the local explanation weights.

    The ``backend`` attribute records which inference method produced this explanation.
    MCMC explanations carry a ``posterior_draws_`` attribute with raw samples, enabling
    richer diagnostics beyond what the analytical posterior provides.
    """

    def __init__(
        self,
        feature_names: List[str],
        intercept_mean: float,
        intercept_var: float,
        coef_mean: np.ndarray,
        coef_cov: np.ndarray,
        instance: np.ndarray,
        prediction: Union[float, np.ndarray],
        credible_mass: float = 0.95,
        backend: str = "analytical",
        posterior_draws: Optional[np.ndarray] = None,
        hdi_lower: Optional[np.ndarray] = None,
        hdi_upper: Optional[np.ndarray] = None,
    ):
        self.feature_names = feature_names
        self.intercept_mean = intercept_mean
        self.intercept_var = intercept_var
        self.coef_mean = coef_mean
        self.coef_cov = coef_cov
        self.coef_std = np.sqrt(np.diag(coef_cov))
        self.instance = instance
        self.prediction = prediction
        self.credible_mass = credible_mass
        self.backend = backend

        # MCMC-only: raw posterior draws over coefficients (shape: n_draws x n_features)
        self.posterior_draws_ = posterior_draws

        # Pre-computed HDI bounds (MCMC path); None for analytical path
        self._hdi_lower = hdi_lower
        self._hdi_upper = hdi_upper

    def credible_intervals(self, credible_mass: Optional[float] = None) -> Dict[str, Tuple[float, float]]:
        """Compute the credible interval bounds for each feature coefficient.

        For the analytical backend, uses the Normal marginal posterior.
        For the MCMC backend, uses HDI computed from posterior draws.
        """
        mass = credible_mass if credible_mass is not None else self.credible_mass

        if self.backend == "mcmc" and self.posterior_draws_ is not None:
            lower, upper = compute_hdi(self.posterior_draws_, mass)
        else:
            q_lower = (1.0 - mass) / 2.0
            q_upper = 1.0 - q_lower
            lower = np.array([
                stats.norm.ppf(q_lower, loc=self.coef_mean[i], scale=self.coef_std[i])
                for i in range(len(self.feature_names))
            ])
            upper = np.array([
                stats.norm.ppf(q_upper, loc=self.coef_mean[i], scale=self.coef_std[i])
                for i in range(len(self.feature_names))
            ])

        return {
            name: (float(lower[i]), float(upper[i]))
            for i, name in enumerate(self.feature_names)
        }

    def as_list(self) -> List[Tuple[str, float]]:
        """Return the explanation as a sorted list of (feature_name, mean_weight) tuples."""
        pairs = list(zip(self.feature_names, self.coef_mean))
        return sorted(pairs, key=lambda x: abs(x[1]), reverse=True)

    def as_dataframe(self, credible_mass: Optional[float] = None) -> pd.DataFrame:
        """Return a summary of local explanation weights as a pandas DataFrame.

        Includes posterior mean, standard deviation, credible interval bounds,
        the feature value for the explained instance, and the backend used.
        """
        mass = credible_mass if credible_mass is not None else self.credible_mass
        intervals = self.credible_intervals(mass)

        data = []
        for idx, name in enumerate(self.feature_names):
            lower, upper = intervals[name]
            data.append({
                "feature": name,
                "mean": self.coef_mean[idx],
                "std": self.coef_std[idx],
                "hdi_lower": lower,
                "hdi_upper": upper,
                "value": self.instance[idx],
                "backend": self.backend,
            })

        df = pd.DataFrame(data)
        df["abs_mean"] = df["mean"].abs()
        df = df.sort_values("abs_mean", ascending=False).drop(columns=["abs_mean"])
        return df.reset_index(drop=True)

    def plot(self, credible_mass: Optional[float] = None, max_features: int = 10) -> Any:
        """Plot the explanation as a horizontal bar chart with credible intervals.

        Requires matplotlib.
        """
        try:
            import matplotlib.pyplot as plt
        except ImportError:
            raise ImportError("matplotlib is required to plot explanations. Install it with pip.")

        df = self.as_dataframe(credible_mass).head(max_features)
        df = df.iloc[::-1]  # Invert so largest is at the top

        fig, ax = plt.subplots(figsize=(8, len(df) * 0.4 + 1.5))

        errors_lower = df["mean"] - df["hdi_lower"]
        errors_upper = df["hdi_upper"] - df["mean"]
        xerr = np.vstack([errors_lower, errors_upper])

        colors = ["#1f77b4" if m >= 0 else "#d62728" for m in df["mean"]]

        ax.barh(
            df["feature"],
            df["mean"],
            xerr=xerr,
            color=colors,
            alpha=0.8,
            error_kw={"ecolor": "dimgray", "capsize": 3, "lw": 1.5},
        )

        ax.axvline(0, color="black", linestyle="--", linewidth=1)
        ax.set_xlabel("Local Feature Importance (Posterior Mean)")
        backend_label = f"backend={self.backend}"
        ax.set_title(
            f"BayLIME Explanation "
            f"(credible_mass={credible_mass if credible_mass else self.credible_mass}, {backend_label})"
        )
        plt.tight_layout()
        return fig


class BayLIME(BaseEstimator):
    """BayLIME Local Surrogate Explainer.

    Generates stable, prior-informed local explanations for any black-box model
    by fitting a Bayesian surrogate to a perturbed local neighborhood.

    Two backends are supported:

    ``backend='analytical'`` (default)
        Fits a closed-form weighted Bayesian linear regression. Requires only
        ``numpy`` and ``scipy``. Suitable for high-throughput explanation workloads
        and assumes homoscedastic Gaussian noise.

    ``backend='mcmc'``
        Builds a PyMC probabilistic model with a heteroscedastic noise structure
        where observation variance is modulated by proximity weights
        (``obs_sigma = sigma_global / sqrt(proximity_weights)``). This captures the
        geometric intuition that nearby perturbations should constrain the surrogate
        more tightly than distant ones. Requires the ``mcmc`` optional extra
        (``uv sync --extra mcmc`` or ``pip install bxai[mcmc]``).

        The MCMC backend also supports an optional sparsity-inducing Horseshoe prior
        on local coefficients (``mcmc_prior='horseshoe'``), automatically suppressing
        noise features in the local neighborhood without manual regularization tuning.

    Parameters
    ----------
    training_data : array-like
        The training data used to compute feature scales for perturbation.
    feature_names : list of str, optional
        Names for each feature. Defaults to ``feature_0, feature_1, ...``.
    kernel_width : float, default=0.75
        Width of the exponential distance kernel controlling proximity weight decay.
    num_samples : int, default=5000
        Number of perturbed samples to generate per explanation.
    prior_mean : np.ndarray, optional
        Prior mean over feature coefficients (shape: ``(n_features,)``). Feed global
        SHAP values from BayesianBorutaSHAP here to ground local explanations.
    prior_precision : float or np.ndarray, optional
        Prior precision (inverse variance) for feature coefficients. A scalar applies
        the same precision to all features; an array allows per-feature control.
        Ignored when ``backend='mcmc'`` and ``mcmc_prior='horseshoe'``.
    backend : str, default='analytical'
        Inference backend. One of ``'analytical'`` or ``'mcmc'``.
    mcmc_prior : str, default='normal'
        Prior type for MCMC backend coefficients. One of ``'normal'`` or ``'horseshoe'``.
        Ignored when ``backend='analytical'``.
    mcmc_samples : int, default=1000
        Number of posterior draw samples (MCMC backend only).
    mcmc_tune : int, default=500
        Number of MCMC tuning steps (MCMC backend only).
    mcmc_chains : int, default=2
        Number of MCMC chains (MCMC backend only).
    progressbar : bool, default=False
        Whether to show the PyMC sampling progress bar (MCMC backend only).
    random_state : int, optional
        Seed for perturbation sampling and MCMC reproducibility.
    """

    def __init__(
        self,
        training_data: Any,
        feature_names: Optional[List[str]] = None,
        kernel_width: float = 0.75,
        num_samples: int = 5000,
        prior_mean: Optional[np.ndarray] = None,
        prior_precision: Optional[Union[float, np.ndarray]] = None,
        backend: str = "analytical",
        mcmc_prior: str = "normal",
        mcmc_samples: int = 1000,
        mcmc_tune: int = 500,
        mcmc_chains: int = 2,
        progressbar: bool = False,
        random_state: Optional[int] = None,
    ):
        # sklearn convention: __init__ only assigns parameters to self.
        # Validation and derived attributes live in _setup(), called lazily
        # from explain_instance().  This keeps get_params() / set_params() /
        # clone() working correctly — BaseEstimator.get_params() inspects the
        # __init__ signature and expects each parameter name to map 1-to-1 to
        # a same-named attribute without side-effects.
        self.training_data = training_data
        self.feature_names = feature_names
        self.kernel_width = kernel_width
        self.num_samples = num_samples
        self.prior_mean = prior_mean
        self.prior_precision = prior_precision
        self.backend = backend
        self.mcmc_prior = mcmc_prior
        self.mcmc_samples = mcmc_samples
        self.mcmc_tune = mcmc_tune
        self.mcmc_chains = mcmc_chains
        self.progressbar = progressbar
        self.random_state = random_state

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _setup(self) -> None:
        """Validate parameters and compute derived attributes.

        Called from :meth:`explain_instance` the first time it is invoked so
        that ``__init__`` remains a pure parameter-assignment method (required
        for ``BaseEstimator.get_params`` / ``set_params`` / ``clone`` to work).
        Subsequent calls are no-ops, so repeated :meth:`explain_instance` calls
        incur no extra cost.

        Only the summary statistics needed for perturbation (``means_`` and
        ``stds_``) are stored; the full validated array is discarded immediately
        after extraction to avoid retaining a potentially large copy in memory.
        """
        if hasattr(self, "_n_features"):
            return  # already set up

        if self.backend not in ("analytical", "mcmc"):
            raise ValueError("backend must be 'analytical' or 'mcmc'")
        if self.mcmc_prior not in ("normal", "horseshoe"):
            raise ValueError("mcmc_prior must be 'normal' or 'horseshoe'")

        training_data = check_array_2d(self.training_data)
        self._n_features = training_data.shape[1]

        feature_names = self.feature_names
        if feature_names is not None:
            if len(feature_names) != self._n_features:
                raise ValueError(
                    f"Length of feature_names ({len(feature_names)}) must match "
                    f"n_features ({self._n_features})"
                )
            self._feature_names = list(feature_names)
        else:
            self._feature_names = [f"feature_{i}" for i in range(self._n_features)]

        # Compute and store only the summary statistics needed for perturbation.
        # The validated array is *not* retained — storing it would keep an
        # O(n_samples × n_features) copy alive for the lifetime of the object.
        self.means_ = np.mean(training_data, axis=0)
        self.stds_ = np.std(training_data, axis=0)
        self.stds_[self.stds_ == 0.0] = 1.0

    def _perturb(
        self,
        instance: np.ndarray,
        noise_scale: float,
        rng: np.random.Generator,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Generate local neighborhood and compute proximity weights."""
        noise = rng.normal(0.0, noise_scale, size=(self.num_samples, self._n_features))
        Z = instance + noise * self.stds_
        Z[0] = instance  # anchor first sample to instance

        Z_normalized = (Z - instance) / self.stds_
        distances = np.linalg.norm(Z_normalized, axis=1)
        proximity_weights = np.exp(-(distances ** 2) / (self.kernel_width ** 2))

        return Z, proximity_weights, distances

    def _explain_analytical(
        self,
        Z: np.ndarray,
        y: np.ndarray,
        proximity_weights: np.ndarray,
        instance: np.ndarray,
        preds: np.ndarray,
    ) -> BayLIMEExplanation:
        """Closed-form weighted Bayesian linear regression backend."""
        p = self._n_features

        # Augment with intercept column
        X = np.hstack([np.ones((len(Z), 1)), Z])

        # Prior mean vector
        mu_theta_0 = np.zeros(p + 1)
        if self.prior_mean is not None:
            prior_m = np.asarray(self.prior_mean).ravel()
            if len(prior_m) != p:
                raise ValueError(
                    f"prior_mean length ({len(prior_m)}) must match n_features ({p})"
                )
            mu_theta_0[1:] = prior_m


        # Prior precision matrix
        Sigma_0_inv = np.zeros((p + 1, p + 1))
        Sigma_0_inv[0, 0] = 1e-4  # flat intercept prior
        if self.prior_precision is None:
            np.fill_diagonal(Sigma_0_inv[1:, 1:], 1.0)
        elif isinstance(self.prior_precision, (int, float)):
            np.fill_diagonal(Sigma_0_inv[1:, 1:], float(self.prior_precision))
        else:
            prior_p = np.asarray(self.prior_precision).ravel()
            if len(prior_p) != p:
                raise ValueError(
                    f"prior_precision length ({len(prior_p)}) must match n_features ({p})"
                )
            np.fill_diagonal(Sigma_0_inv[1:, 1:], prior_p)

        # Weighted sufficient statistics
        X_w = X * proximity_weights[:, np.newaxis]
        XTWX = X_w.T @ X
        XTWy = X_w.T @ y

        # Posterior
        try:
            Sigma_n = np.linalg.inv(XTWX + Sigma_0_inv)
        except np.linalg.LinAlgError:
            Sigma_n = np.linalg.pinv(XTWX + Sigma_0_inv)

        mu_n = Sigma_n @ (XTWy + Sigma_0_inv @ mu_theta_0)

        return BayLIMEExplanation(
            feature_names=self._feature_names,
            intercept_mean=float(mu_n[0]),
            intercept_var=float(Sigma_n[0, 0]),
            coef_mean=mu_n[1:],
            coef_cov=Sigma_n[1:, 1:],
            instance=instance,
            prediction=preds[0],
            backend="analytical",
        )

    def _explain_mcmc(
        self,
        Z: np.ndarray,
        y: np.ndarray,
        proximity_weights: np.ndarray,
        instance: np.ndarray,
        preds: np.ndarray,
    ) -> BayLIMEExplanation:
        """PyMC heteroscedastic MCMC backend.

        Models observation noise as inversely proportional to proximity weight:
            obs_sigma_i = sigma_global / sqrt(proximity_weight_i)

        This reflects the natural geometry of LIME: samples close to the instance
        should tightly constrain the surrogate; distant samples contribute weakly.
        """
        try:
            import pymc as pm
            import pytensor.tensor as pt
        except ImportError:
            raise ImportError(
                "pymc is required for the 'mcmc' backend. "
                "Install it with `pip install 'bxai[mcmc]'` or `uv sync --extra mcmc`."
            )

        p = self._n_features

        # Build prior mean vector
        prior_mean_vec = np.zeros(p)
        if self.prior_mean is not None:
            prior_m = np.asarray(self.prior_mean).ravel()
            if len(prior_m) != p:
                raise ValueError(
                    f"prior_mean length ({len(prior_m)}) must match n_features ({p})"
                )
            prior_mean_vec = prior_m

        # Clamp proximity weights away from zero to avoid numerical issues
        pw_safe = np.clip(proximity_weights, 1e-8, None)

        with pm.Model():
            Z_data = pm.Data("Z", Z)
            y_data = pm.Data("y", y)
            pw_data = pm.Data("proximity_weights", pw_safe)

            intercept = pm.Normal("intercept", mu=0.0, sigma=5.0)

            # Feature coefficient priors
            if self.mcmc_prior == "horseshoe":
                # Global and local shrinkage -- Horseshoe prior
                tau = pm.HalfCauchy("tau", beta=1.0)
                lambdas = pm.HalfCauchy("lambdas", beta=1.0, shape=p)
                coefs = pm.Normal(
                    "coefs",
                    mu=prior_mean_vec,
                    sigma=tau * lambdas,
                    shape=p,
                )
            else:
                # Normal prior with optional prior precision control
                if self.prior_precision is None:
                    sigma_prior = 1.0
                elif isinstance(self.prior_precision, (int, float)):
                    # prior_precision is inverse variance, so sigma = 1/sqrt(precision)
                    sigma_prior = 1.0 / np.sqrt(float(self.prior_precision))
                else:
                    sigma_prior = 1.0 / np.sqrt(
                        np.asarray(self.prior_precision, dtype=float).ravel()
                    )

                coefs = pm.Normal(
                    "coefs",
                    mu=prior_mean_vec,
                    sigma=sigma_prior,
                    shape=p,
                )

            # Global noise scale -- shared across all observations
            sigma_global = pm.HalfNormal("sigma_global", sigma=1.0)

            # Heteroscedastic observation noise:
            # obs_sigma_i = sigma_global / sqrt(proximity_weight_i)
            # High proximity -> small sigma -> tighter constraint on surrogate
            obs_sigma = sigma_global / pt.sqrt(pw_data)

            # Linear prediction
            mu_pred = intercept + pm.math.dot(Z_data, coefs)

            # Likelihood
            pm.Normal("y_obs", mu=mu_pred, sigma=obs_sigma, observed=y_data)

            trace = pm.sample(
                draws=self.mcmc_samples,
                tune=self.mcmc_tune,
                chains=self.mcmc_chains,
                random_seed=self.random_state,
                progressbar=self.progressbar,
                return_inferencedata=True,
            )

        # Extract posterior draws: shape (chains * draws, p)
        coef_draws = trace.posterior["coefs"].values  # (chains, draws, p)
        coef_flat = coef_draws.reshape(-1, p)

        intercept_draws = trace.posterior["intercept"].values.ravel()

        coef_mean = coef_flat.mean(axis=0)
        coef_cov = np.cov(coef_flat.T) if p > 1 else np.atleast_2d(coef_flat.var())
        intercept_mean = float(intercept_draws.mean())
        intercept_var = float(intercept_draws.var())

        # Pre-compute HDI at the requested credible mass
        hdi_lower, hdi_upper = compute_hdi(coef_flat, credible_mass=0.95)

        return BayLIMEExplanation(
            feature_names=self._feature_names,
            intercept_mean=intercept_mean,
            intercept_var=intercept_var,
            coef_mean=coef_mean,
            coef_cov=coef_cov,
            instance=instance,
            prediction=preds[0],
            backend="mcmc",
            posterior_draws=coef_flat,
            hdi_lower=hdi_lower,
            hdi_upper=hdi_upper,
        )

    def explain_instance(
        self,
        instance: np.ndarray,
        predict_fn: Callable[[np.ndarray], np.ndarray],
        label: int = 1,
        noise_scale: float = 0.1,
    ) -> BayLIMEExplanation:
        """Generate a BayLIME explanation for a single instance.

        Dispatches to the analytical or MCMC backend depending on the
        ``backend`` parameter set at construction time.

        Parameters
        ----------
        instance : np.ndarray
            The 1D instance vector to explain. Shape: (n_features,).
        predict_fn : Callable
            The prediction function of the black-box model. Must accept a 2D
            array and return either a 1D array (regression) or 2D array of
            class probabilities (classification).
        label : int, default=1
            The column index of the prediction output to explain. For binary
            classification, this is typically 1 (positive class probability).
        noise_scale : float, default=0.1
            Scale of Gaussian noise applied to generate the local neighborhood.
            Multiplied element-wise by the training data standard deviations.
        """
        self._setup()

        instance = np.asarray(instance, dtype=float).ravel()
        if len(instance) != self._n_features:
            raise ValueError(
                f"Instance length ({len(instance)}) must match n_features ({self._n_features})"
            )

        rng = np.random.default_rng(self.random_state)

        # Generate local neighborhood and proximity weights
        Z, proximity_weights, _ = self._perturb(instance, noise_scale, rng)

        # Obtain black-box predictions
        preds = predict_fn(Z)
        y = preds if preds.ndim == 1 else preds[:, label]

        if self.backend == "analytical":
            return self._explain_analytical(Z, y, proximity_weights, instance, preds)
        else:
            return self._explain_mcmc(Z, y, proximity_weights, instance, preds)
